# 🐬 IMPORTATIONS & CHARGEMENT DES DONNEES

In [1]:
import pandas as pd

# import datetime as dt

from IPython.display import display

from sqlalchemy import create_engine, inspect, text

import sys

# !pip install unidecode
# from unidecode import unidecode
import os
from tools import *

In [2]:
olap_extract_file = "../data/Extraction+cube+OLAP+-+14+aout+2024.xlsx"
log_file = "../data/Logs.xlsx"

df_vente =      pd.read_excel(olap_extract_file, sheet_name='Vente Détail', dtype={'EAN': str})
df_produit =    pd.read_excel(olap_extract_file, sheet_name='Produits', dtype={'EAN': str})
df_client =     pd.read_excel(olap_extract_file, sheet_name='Clients')
df_calendrier = pd.read_excel(olap_extract_file, sheet_name='Calendrier')
df_employe =    pd.read_excel(olap_extract_file, sheet_name='Employé')


# Chargement de fichier log
# Force les colonnes ID en string pour préserver le format original. Évite : "000123" -> 123 ou "007" -> 7
df_log = pd.read_excel(log_file, dtype={'id_user': str, 'id_ligne': str});

df_vente_raw  = df_vente.copy()
df_produit_raw = df_produit.copy()
df_client_raw = df_client.copy()
df_calendrier_raw = df_calendrier.copy()
df_employe_raw = df_employe.copy()
df_log_raw= df_log.copy()

print(f"Taille de df_vente_raw : {df_vente_raw.shape}")
print(f"Taille de df_produit_raw : {df_produit_raw.shape}")
print(f"Taille de df_client_raw : {df_client_raw.shape}")
print(f"Taille de df_calendrier_raw : {df_calendrier_raw.shape}")
print(f"Taille de df_employe_raw : {df_employe_raw.shape}")
print(f"Taille de df_log_raw : {df_log_raw.shape}")

print("Fichiers sont chargés correctements")

Taille de df_vente_raw : (41377, 6)
Taille de df_produit_raw : (18040, 5)
Taille de df_client_raw : (2297, 2)
Taille de df_calendrier_raw : (1999, 8)
Taille de df_employe_raw : (56, 7)
Taille de df_log_raw : (207489, 7)
Fichiers sont chargés correctements

# ⚙️PARAMETRES

In [3]:
pd.set_option('display.float_format', '{:.2f}'.format)

# 💰 VENTES (41 377, 6)

In [4]:
get_duplicates_in_subset(df = df_vente, verbose=True)
get_possible_candidates(df_vente, verbose=True)

✅ Aucun doublon trouvé

#### 🔍 Analyse des colonnes pour trouver des clés candidates

> **🎯 1 clé candidate(s) trouvée(s) :**
>
> - ✅ `ID_BDD`

['ID_BDD']

In [5]:
df_vente.columns

Index(['ID_BDD', 'CUSTOMER_ID', 'id_employe', 'EAN', 'Date achat',
       'ID ticket'],
      dtype='object')

## 🏷️: ID_BDD

In [6]:
display_stats(df_vente, columns='ID_BDD')

---

**Colonne: ID_BDD**

🔍 Type réel: object
📊 Mémoire: 3.31 MB
Longueur min du texte: 35
Longueur max du texte: 35
Valeurs uniques: 41377
Valeurs les plus fréquentes:

                                     count
ID_BDD
HZDG8U15NNY7SI6HDK8NMFDEK7MOVUX31VY      1
1H51BRR800TK9DCIH8M9QCRH3LEAR0JWALJ      1
W6VNWK6ZX0D4QZ545ZD5Y0THWQQDBTXABXO      1
58EC3JD1TDZZAVQZAW4AHFOUEKTR61ZLB70      1
96FE6HA91BRDDF6XRI3O9B83M5PKIXCIXZV      1

✅ Pas de valeurs manquantes dans la colonne 'ID_BDD'

In [7]:
display_stats(df_vente, columns='CUSTOMER_ID')

---

**Colonne: CUSTOMER_ID**

🔍 Type réel: object
📊 Mémoire: 2.60 MB
Longueur min du texte: 17
Longueur max du texte: 17
Valeurs uniques: 2297
Valeurs les plus fréquentes:

                   count
CUSTOMER_ID
CUST-XN844ZWFIJAB     44
CUST-4156OAAI6FZD     44
CUST-M345YIVLJK94     44
CUST-7WAMOE5MZR4Q     44
CUST-I748P44RCYV2     43

✅ Pas de valeurs manquantes dans la colonne 'CUSTOMER_ID'

## 🏷️: CUSTOMER_ID

In [8]:
display_stats(df_vente, columns='CUSTOMER_ID')

---

**Colonne: CUSTOMER_ID**

🔍 Type réel: object
📊 Mémoire: 2.60 MB
Longueur min du texte: 17
Longueur max du texte: 17
Valeurs uniques: 2297
Valeurs les plus fréquentes:

                   count
CUSTOMER_ID
CUST-XN844ZWFIJAB     44
CUST-4156OAAI6FZD     44
CUST-M345YIVLJK94     44
CUST-7WAMOE5MZR4Q     44
CUST-I748P44RCYV2     43

✅ Pas de valeurs manquantes dans la colonne 'CUSTOMER_ID'

## 🏷️: id_employe

In [9]:
display_stats(df_vente, columns='id_employe')

---

**Colonne: id_employe**

🔍 Type réel: object
📊 Mémoire: 3.20 MB
Longueur min du texte: 32
Longueur max du texte: 32
Valeurs uniques: 56
Valeurs les plus fréquentes:

                                  count
id_employe
f491076a1ff2d873ebea809c11144542   1100
e01e752175e05f00c8314ccb8da4c418   1077
8d1001fbad3d2a60ff7530600ed5d55e    951
a7ada0770091e838e3dcd45265282820    943
6c1c3292c852c6c593b95cc146b00c0e    929

✅ Pas de valeurs manquantes dans la colonne 'id_employe'

## 🏷️: EAN

In [10]:
display_stats(df_vente, columns='EAN')

---

**Colonne: EAN**

🔍 Type réel: object
📊 Mémoire: 2.44 MB
Longueur min du texte: 9
Longueur max du texte: 13
Valeurs uniques: 16146
Valeurs les plus fréquentes:

               count
EAN
8318765076329     11
912146245221      10
5689766860863     10
3914221243055     10
9157542401590      9

✅ Pas de valeurs manquantes dans la colonne 'EAN'

In [11]:
df_vente

,ID_BDD,CUSTOMER_ID,id_employe,EAN,Date achat,ID ticket
0,HZDG8U15NNY7SI6HDK8NMFDEK7MOVUX31VY,CUST-G42Z6WE8QLWJ,b413ca065a762e8cf2e86cfea8b9c174,6473630445822,45518,t_2693
1,1H51BRR800TK9DCIH8M9QCRH3LEAR0JWALJ,CUST-CUA37GP8GABQ,a7ada0770091e838e3dcd45265282820,1857802002765,45518,t_4408
2,W6VNWK6ZX0D4QZ545ZD5Y0THWQQDBTXABXO,CUST-NHWI0DGNESYI,fa836e3f5faf72d24e079235332169ce,6831886714876,45518,t_3258
3,58EC3JD1TDZZAVQZAW4AHFOUEKTR61ZLB70,CUST-IYXDMN7Q11O4,6c1c3292c852c6c593b95cc146b00c0e,6916826750723,45518,t_1080
4,96FE6HA91BRDDF6XRI3O9B83M5PKIXCIXZV,CUST-VR9O54A46EVF,38680e129f45c49322cb12303b7fb655,7930902861368,45518,t_979
...,...,...,...,...,...,...
41372,MCGOLHNLDKZLZBQWC0KWEGBRUJS5BB9U6NM,CUST-LJUSB06MJC1A,2477db17c02f512ebc4b20f01a7edb55,4553383105782,45518,t_3968
41373,EUY9WJVL4U4XMBZLLIKVMCLQ38ZYN0AL4UC,CUST-4W2BZS8DRM78,c495d16c3108a11ac8318269a85e9706,8867736611198,45518,t_1388
41374,BAIEOXQOGUIWXQ68OAHPUAHCQ4RRY6J1XT4,CUST-KSFK8ZZAHCRB,9f29007d63c46217deeb64efc81eba9e,9018928246844,45518,t_2603
41375,7H9YA3NO6IDLUZVEI6XGUV656XM5DCW5HO7,CUST-TELCAOFC3TA5,f491076a1ff2d873ebea809c11144542,4867790358975,45518,t_3337
41376,58FD4IVY9EE0UZMH71SBQDE09FG9GG15U9P,CUST-ZZGXQ2ATTLTY,f93c7cff0b2eeb5ff91eba8606f78297,9253834950950,45518,t_3637

## 🏷️: Date achat

In [12]:
# df_vente["Date achat"] = pd.to_datetime(df_vente["Date achat"], unit='D', origin='1899-12-30')
display_stats(df_vente, columns='Date achat')

---

**Colonne: Date achat**

🔍 Type réel: int64
📊 Mémoire: 0.32 MB

✅ Pas de valeurs manquantes dans la colonne 'Date achat'

## 🏷️: ID ticket

In [13]:
display_stats(df_vente, columns='ID ticket')

---

**Colonne: ID ticket**

🔍 Type réel: object
📊 Mémoire: 2.16 MB
Longueur min du texte: 3
Longueur max du texte: 6
Valeurs uniques: 1808
Valeurs les plus fréquentes:

           count
ID ticket
t_3960        86
t_4588        85
t_4481        84
t_4641        79
t_2169        79

✅ Pas de valeurs manquantes dans la colonne 'ID ticket'

In [14]:
mask = df_vente["ID ticket"].str.len() == 3
df_vente.loc[mask, "ID ticket"]

594      t_9
1058     t_7
4608     t_9
4702     t_8
6051     t_9
        ...
39704    t_7
39750    t_9
39752    t_9
40515    t_7
40621    t_9
Name: ID ticket, Length: 74, dtype: object

# 📦 PRODUITS (18 040, 5)

In [15]:
get_duplicates_in_subset(df = df_produit_raw, verbose=True)
get_possible_candidates(df_produit_raw, verbose=True)

✅ Aucun doublon trouvé

#### 🔍 Analyse des colonnes pour trouver des clés candidates

> **🎯 1 clé candidate(s) trouvée(s) :**
>
> - ✅ `EAN`

['EAN']

## 🏷️: EAN

In [16]:
display_stats(df_produit_raw, columns='EAN')

---

**Colonne: EAN**

🔍 Type réel: object
📊 Mémoire: 1.06 MB
Longueur min du texte: 9
Longueur max du texte: 13
Valeurs uniques: 18040
Valeurs les plus fréquentes:

               count
EAN
5026767366043      1
1002603715237      1
2113941413715      1
2597945667827      1
8046456922921      1

✅ Pas de valeurs manquantes dans la colonne 'EAN'

In [17]:
df_produit_raw["EAN"].str.len().value_counts().sort_index()

EAN
9         2
10       27
11      163
12     1614
13    16234
Name: count, dtype: int64

In [18]:
# Les codes EAN à 9 chiffres
mask = df_produit_raw['EAN'].str.len() == 9
df_produit_raw.loc[mask, 'EAN']

6235     738913053
16382    348229101
Name: EAN, dtype: object

## 🏷️: categorie

In [19]:
display_stats(df_produit_raw, columns='categorie')

---

**Colonne: categorie**

🔍 Type réel: object
📊 Mémoire: 1.54 MB
Longueur min du texte: 8
Longueur max du texte: 28
Valeurs uniques: 15
Valeurs les plus fréquentes:

                              count
categorie
Produits Secs & Conserves      4566
Hygiène & Parfumerie           3322
Cosmétiques & Maquillage       1756
Boissons                       1431
Produits Laitiers & Crèmerie   1342

✅ Pas de valeurs manquantes dans la colonne 'categorie'

## 🏷️: Rayon

In [20]:
display_stats(df_produit_raw, columns='Rayon')

---

**Colonne: Rayon**

🔍 Type réel: object
📊 Mémoire: 1.04 MB
Longueur min du texte: 3
Longueur max du texte: 34
Valeurs uniques: 128
Valeurs les plus fréquentes:

                                    count
Rayon
l'oreal                               644
plats cuisines                        628
gemey                                 613
produits dietetiques et biologique    538
patisseries                           504

✅ Pas de valeurs manquantes dans la colonne 'Rayon'

## 🏷️: Libelle_produit

In [21]:
display_stats(df_produit_raw, columns='Libelle_produit')

---

**Colonne: Libelle_produit**

🔍 Type réel: object
📊 Mémoire: 1.33 MB
Longueur min du texte: 6
Longueur max du texte: 30
Valeurs uniques: 17972
Valeurs les plus fréquentes:

                                count
Libelle_produit
cover stick  beige bl               3
70cl pastis henri bardouin 45›      2
4 tr. jambon le superieur a.c.      2
4 tr. blanc de dinde dore au f      2
20cl fruit shoot orange pet         2

✅ Pas de valeurs manquantes dans la colonne 'Libelle_produit'

## 🏷️: prix

In [22]:
display_stats(df_produit_raw, columns='prix')

---

**Colonne: prix**

🔍 Type réel: float64
📊 Mémoire: 0.14 MB

✅ Pas de valeurs manquantes dans la colonne 'prix'

# 👥 CLIENTS  (2 297, 2)

In [23]:
get_duplicates_in_subset(df = df_client_raw, verbose=True)
get_possible_candidates(df_client_raw, verbose=True)

✅ Aucun doublon trouvé

#### 🔍 Analyse des colonnes pour trouver des clés candidates

> **🎯 1 clé candidate(s) trouvée(s) :**
>
> - ✅ `CUSTUMER_ID`

['CUSTUMER_ID']

## 🏷️: CUSTUMER_ID

In [24]:
display_stats(df_client, columns="CUSTUMER_ID")

---

**Colonne: CUSTUMER_ID**

🔍 Type réel: object
📊 Mémoire: 0.14 MB
Longueur min du texte: 17
Longueur max du texte: 17
Valeurs uniques: 2297
Valeurs les plus fréquentes:

                   count
CUSTUMER_ID
CUST-2KYXXXW1NK7I      1
CUST-NR43XRT2PXYG      1
CUST-CH58P8PSVIYU      1
CUST-CI7JQHW4TIYT      1
CUST-3QHP3KL4NPP2      1

✅ Pas de valeurs manquantes dans la colonne 'CUSTUMER_ID'

## 🏷️: date_inscription

In [25]:
df_client["date_inscription_date"] = pd.to_datetime(df_client["date_inscription"] ,format='%d%m%Y').dt.date
display_stats(df_client, columns=["date_inscription","date_inscription_date"])

---

**Colonne: date_inscription**

🔍 Type réel: datetime64[ns]
Période: 2020-01-01 00:00:00 à 2024-08-14 00:00:00
📊 Mémoire: 0.02 MB
Longueur min du texte: 10
Longueur max du texte: 10
Valeurs uniques: 1256
Valeurs les plus fréquentes:

                  count
date_inscription
2024-08-14           20
2023-02-22            6
2024-05-18            6
2023-08-29            6
2020-03-18            6

✅ Pas de valeurs manquantes dans la colonne 'date_inscription'

---

**Colonne: date_inscription_date**

🔍 Type réel: object
📊 Mémoire: 0.09 MB
Longueur min du texte: 10
Longueur max du texte: 10
Valeurs uniques: 1256
Valeurs les plus fréquentes:

                       count
date_inscription_date
2024-08-14                20
2023-02-22                 6
2024-05-18                 6
2023-08-29                 6
2020-03-18                 6

✅ Pas de valeurs manquantes dans la colonne 'date_inscription_date'

#  📅 CALENDAR (1 999, 8)

In [26]:
get_duplicates_in_subset(df = df_calendrier_raw, verbose=True)
get_possible_candidates(df_calendrier_raw, verbose=True)

✅ Aucun doublon trouvé

#### 🔍 Analyse des colonnes pour trouver des clés candidates

> **🎯 1 clé candidate(s) trouvée(s) :**
>
> - ✅ `date`

['date']

## 🏷️: date

In [27]:
display_stats(df_calendrier, columns='date')

---

**Colonne: date**

🔍 Type réel: int64
📊 Mémoire: 0.02 MB

✅ Pas de valeurs manquantes dans la colonne 'date'

## 🏷️: full_date

Champ calculé correspondant à la convertion de date_id en format DATE.

In [28]:
df_calendrier['full_date'] = pd.to_datetime(df_calendrier['date'], unit='D', origin='1899-12-30')

In [29]:
# 01/01/2020((numéro 43831)) et 21/06/2025(numéro 45829) correspondent à la plage des données sources.
display_stats(df_calendrier, columns='full_date')

---

**Colonne: full_date**

🔍 Type réel: datetime64[ns]
Période: 2020-01-01 00:00:00 à 2025-06-21 00:00:00
📊 Mémoire: 0.02 MB
Longueur min du texte: 10
Longueur max du texte: 10
Valeurs uniques: 1999
Valeurs les plus fréquentes:

            count
full_date
2020-01-01      1
2020-01-02      1
2020-01-03      1
2020-01-04      1
2020-01-05      1

✅ Pas de valeurs manquantes dans la colonne 'full_date'

## 🏷️: annee

In [30]:
display_stats(df_calendrier, columns='annee')

---

**Colonne: annee**

🔍 Type réel: int64
📊 Mémoire: 0.02 MB

✅ Pas de valeurs manquantes dans la colonne 'annee'

## 🏷️: mois

In [31]:
display_stats(df_calendrier, columns='mois')

---

**Colonne: mois**

🔍 Type réel: int64
📊 Mémoire: 0.02 MB

✅ Pas de valeurs manquantes dans la colonne 'mois'

## 🏷️: Jour

In [32]:
display_stats(df_calendrier, columns='Jour')

---

**Colonne: Jour**

🔍 Type réel: datetime64[ns]
Période: 1900-01-01 00:00:00 à 1900-01-31 00:00:00
📊 Mémoire: 0.02 MB
Longueur min du texte: 10
Longueur max du texte: 10
Valeurs uniques: 31
Valeurs les plus fréquentes:

            count
Jour
1900-01-01     66
1900-01-02     66
1900-01-03     66
1900-01-04     66
1900-01-05     66

✅ Pas de valeurs manquantes dans la colonne 'Jour'

In [33]:
# Dans le fichier source excel, le format de la colonne est mal choisi.Très probablement à cause de mal configuration du Cube OLAP.
df_calendrier["Jour"] = df_calendrier["Jour"].dt.day;

In [34]:
# Affichant à nouveau la description de la colonne 
display_stats(df_calendrier, "Jour")

---

**Colonne: Jour**

🔍 Type réel: int32
📊 Mémoire: 0.01 MB
Longueur min du texte: 1
Longueur max du texte: 2
Valeurs uniques: 31
Valeurs les plus fréquentes:

      count
Jour
1        66
2        66
3        66
4        66
5        66

✅ Pas de valeurs manquantes dans la colonne 'Jour'

In [35]:
mask = df_calendrier["Jour"] == 31
# On doit avoir 38, c'est le nombre de jour 31 dans le fichier source
df_calendrier.loc[mask,].shape

(38, 9)

## 🏷️: mois_nom

In [36]:
display_stats(df_calendrier, columns="mois_nom")

---

**Colonne: mois_nom**

🔍 Type réel: object
📊 Mémoire: 0.12 MB
Longueur min du texte: 3
Longueur max du texte: 9
Valeurs uniques: 12
Valeurs les plus fréquentes:

          count
mois_nom
janvier     186
mars        186
mai         186
avril       180
juin        171

✅ Pas de valeurs manquantes dans la colonne 'mois_nom'

## 🏷️: annee_mois

In [37]:
display_stats(df_calendrier, columns="annee_mois")

---

**Colonne: annee_mois**

🔍 Type réel: int64
📊 Mémoire: 0.02 MB

✅ Pas de valeurs manquantes dans la colonne 'annee_mois'

## 🏷️: jour_semaine

In [38]:
display_stats(df_calendrier, columns="jour_semaine")

---

**Colonne: jour_semaine**

🔍 Type réel: int64
📊 Mémoire: 0.02 MB

✅ Pas de valeurs manquantes dans la colonne 'jour_semaine'

## 🏷️: trimestre

In [39]:
display_stats(df_calendrier, columns='trimestre')

---

**Colonne: trimestre**

🔍 Type réel: object
📊 Mémoire: 0.10 MB
Longueur min du texte: 2
Longueur max du texte: 2
Valeurs uniques: 4
Valeurs les plus fréquentes:

           count
trimestre
Q1           542
Q2           537
Q3           460
Q4           460

✅ Pas de valeurs manquantes dans la colonne 'trimestre'

# 👨‍💼 EMPLOYE  (56, 7)

In [40]:
get_duplicates_in_subset(df = df_employe_raw, verbose=True)
get_possible_candidates(df_employe_raw, verbose=True)

✅ Aucun doublon trouvé

#### 🔍 Analyse des colonnes pour trouver des clés candidates

> **🎯 4 clé candidate(s) trouvée(s) :**
>
> - ✅ `id_employe`
> - ✅ `employe`
> - ✅ `hash_mdp`
> - ✅ `mail`

['id_employe', 'employe', 'hash_mdp', 'mail']

## 🏷️: id_employe

In [41]:
display_stats(df_employe, columns='id_employe')

---

**Colonne: id_employe**

🔍 Type réel: object
📊 Mémoire: 0.00 MB
Longueur min du texte: 32
Longueur max du texte: 32
Valeurs uniques: 56
Valeurs les plus fréquentes:

                                  count
id_employe
6fa61d0ecae0b563fef18d36b2039c8e      1
37c6a856b2e14217855d808fbc8e56a7      1
4853b03deab973a1a8e466025bce5b52      1
e44eabec860498a79e675200bc8fa455      1
fa836e3f5faf72d24e079235332169ce      1

✅ Pas de valeurs manquantes dans la colonne 'id_employe'

## 🏷️: employe

In [42]:
display_stats(df_employe, columns='employe')

---

**Colonne: employe**

🔍 Type réel: object
📊 Mémoire: 0.00 MB
Longueur min du texte: 5
Longueur max du texte: 12
Valeurs uniques: 56
Valeurs les plus fréquentes:

           count
employe
lmaret         1
cvérany        1
sdeslys        1
acoquelin      1
egrosjean      1

✅ Pas de valeurs manquantes dans la colonne 'employe'

## 🏷️: prenom

In [43]:
display_stats(df_employe, columns='employe')

---

**Colonne: employe**

🔍 Type réel: object
📊 Mémoire: 0.00 MB
Longueur min du texte: 5
Longueur max du texte: 12
Valeurs uniques: 56
Valeurs les plus fréquentes:

           count
employe
lmaret         1
cvérany        1
sdeslys        1
acoquelin      1
egrosjean      1

✅ Pas de valeurs manquantes dans la colonne 'employe'

## 🏷️: nom

In [44]:
display_stats(df_employe, columns='nom')

---

**Colonne: nom**

🔍 Type réel: object
📊 Mémoire: 0.00 MB
Longueur min du texte: 4
Longueur max du texte: 11
Valeurs uniques: 53
Valeurs les plus fréquentes:

           count
nom
Grosjean       2
Jacquier       2
Rochefort      2
Maret          1
Vérany         1

✅ Pas de valeurs manquantes dans la colonne 'nom'

## 🏷️: date_debut

In [45]:
display_stats(df_employe, columns='date_debut')

---

**Colonne: date_debut**

🔍 Type réel: int64
📊 Mémoire: 0.00 MB

✅ Pas de valeurs manquantes dans la colonne 'date_debut'

In [46]:
# Génere une copie de date_debut au format "date"
df_employe["date_debut_date"] = pd.to_datetime(df_employe["date_debut"], unit='D', origin='1899-12-30')
display_stats(df_employe, columns='date_debut_date')

---

**Colonne: date_debut_date**

🔍 Type réel: datetime64[ns]
Période: 2020-02-28 00:00:00 à 2024-07-04 00:00:00
📊 Mémoire: 0.00 MB
Longueur min du texte: 10
Longueur max du texte: 10
Valeurs uniques: 54
Valeurs les plus fréquentes:

                 count
date_debut_date
2020-03-17           2
2020-06-12           2
2022-11-17           1
2021-07-03           1
2023-09-23           1

✅ Pas de valeurs manquantes dans la colonne 'date_debut_date'

## 🏷️: hash_mdp

In [47]:
display_stats(df_employe, columns='hash_mdp')

---

**Colonne: hash_mdp**

🔍 Type réel: object
📊 Mémoire: 0.00 MB
Longueur min du texte: 32
Longueur max du texte: 32
Valeurs uniques: 56
Valeurs les plus fréquentes:

                                  count
hash_mdp
0373c45921fbaa7530f34b39e71ba93c      1
3e7956190015a301924fb6d7409665a6      1
45154756438492cd025e3e000781e200      1
d0575b3bf61100514cedb05d87a9b689      1
3a366362e4c0016df16dbd2cfb6c7e2a      1

✅ Pas de valeurs manquantes dans la colonne 'hash_mdp'

## 🏷️: mail

In [48]:
display_stats(df_employe, columns='mail')

---

**Colonne: mail**

🔍 Type réel: object
📊 Mémoire: 0.00 MB
Longueur min du texte: 25
Longueur max du texte: 32
Valeurs uniques: 56
Valeurs les plus fréquentes:

                               count
mail
lmaret@supersmartmarket.fr         1
cvérany@supersmartmarket.fr        1
sdeslys@supersmartmarket.fr        1
acoquelin@supersmartmarket.fr      1
egrosjean@supersmartmarket.fr      1

✅ Pas de valeurs manquantes dans la colonne 'mail'

# 🗒️LOGS  (207 489, 8)

In [49]:
df_log.columns

Index(['id_user', 'date', 'action', 'table_insert', 'id_ligne', 'champs',
       'detail'],
      dtype='object')

In [50]:
get_duplicates_in_subset(df = df_log, verbose=True)

✅ Aucun doublon trouvé

Empty DataFrame
Columns: [id_user, date, action, table_insert, id_ligne, champs, detail]
Index: []

In [51]:
get_possible_candidates(df_log, verbose=True)
# save_stats_to_csv(df_log_raw, "log_stats.csv")

#### 🔍 Analyse des colonnes pour trouver des clés candidates

> **❌ Aucune clé candidate trouvée**

## 🏷️: id_user

In [52]:
display_stats(df_log, columns='id_user')

---

**Colonne: id_user**

🔍 Type réel: object
📊 Mémoire: 16.23 MB
Longueur min du texte: 32
Longueur max du texte: 33
Valeurs uniques: 19
Valeurs les plus fréquentes:

                                    count
id_user
08c8b678f8e6f0caz05880ef4ebba10az  207469
6fa61d0ecae0b563fef18d36b2039c8e        2
dd595f0f0b3400df2908f0be7723dad4        2
c4f0909120cfde7086a3c1a56e96a015        1
0859b70a9ca905a870bfccc5f8440ba1        1

✅ Pas de valeurs manquantes dans la colonne 'id_user'

In [53]:
# Normalement, les id_user font 32 charactère mais il y'en a un à 33 charactère.
mask = (df_log["id_user"].str.len() == 33)
df_log.loc[mask, "id_user"].unique()

array(['08c8b678f8e6f0caz05880ef4ebba10az'], dtype=object)

In [54]:
integration_user_id = df_log.loc[mask, "id_user"].unique().item()
print(f"Utilisateur d'intégration responsable de la quasi totalité des modifications dans la base: {integration_user_id}")

Utilisateur d'intégration responsable de la quasi totalité des modifications dans la base: 08c8b678f8e6f0caz05880ef4ebba10az

In [55]:
# On va le renommer pour une meilleure lisibilité
mask = df_log["id_user"] == integration_user_id
df_log.loc[mask, "id_user"] = 'integration_user_id'

## 🏷️: date

In [56]:
display_stats(df_log, columns='date')

---

**Colonne: date**

🔍 Type réel: int64
📊 Mémoire: 1.58 MB

✅ Pas de valeurs manquantes dans la colonne 'date'

In [57]:
df_log["date_date"] = pd.to_datetime(df_log["date"], unit="D", origin="1899-12-30")
display_stats(df_log, columns="date_date")

---

**Colonne: date_date**

🔍 Type réel: datetime64[ns]
Période: 2024-08-14 00:00:00 à 2024-08-15 00:00:00
📊 Mémoire: 1.58 MB
Longueur min du texte: 10
Longueur max du texte: 10
Valeurs uniques: 2
Valeurs les plus fréquentes:

             count
date_date
2024-08-14  200594
2024-08-15    6895

✅ Pas de valeurs manquantes dans la colonne 'date_date'

## 🏷️: action

In [58]:
display_stats(df_log, columns='action')

---

**Colonne: action**

🔍 Type réel: object
📊 Mémoire: 10.88 MB
Longueur min du texte: 6
Longueur max du texte: 6
Valeurs uniques: 3
Valeurs les plus fréquentes:

         count
action
INSERT  206905
UPDATE     582
DELETE       2

✅ Pas de valeurs manquantes dans la colonne 'action'

**Observation**: La totalité des opération DELETE et UPDATE ont été réalisé par l'utisateur d'intégration.

In [59]:
df_log.groupby("action")["id_user"].unique()

action
DELETE                                [integration_user_id]
INSERT    [0859b70a9ca905a870bfccc5f8440ba1, c4f0909120c...
UPDATE                                [integration_user_id]
Name: id_user, dtype: object

## 🏷️: table_insert

In [60]:
display_stats(df_log, columns='table_insert')

---

**Colonne: table_insert**

🔍 Type réel: object
📊 Mémoire: 10.88 MB
Longueur min du texte: 6
Longueur max du texte: 8
Valeurs uniques: 4
Valeurs les plus fréquentes:

               count
table_insert
Ventes        206885
Produits         575
Client            20
Employé            9

✅ Pas de valeurs manquantes dans la colonne 'table_insert'

In [61]:
# Mapping des nom des tables: correspondance entre les noms originaux et les noms standardisés
table_name_map =  {
    'Client': 'dim_customers',
    'Produits': 'dim_products',
    'Ventes': 'fact_sales',
    'Employé': 'dim_employees'
}

df_log['table_insert'] = df_log['table_insert'].map(table_name_map)

# Vérification
display_stats(df_log, columns='table_insert')

---

**Colonne: table_insert**

🔍 Type réel: object
📊 Mémoire: 11.68 MB
Longueur min du texte: 10
Longueur max du texte: 13
Valeurs uniques: 4
Valeurs les plus fréquentes:

                count
table_insert
fact_sales     206885
dim_products      575
dim_customers      20
dim_employees       9

✅ Pas de valeurs manquantes dans la colonne 'table_insert'

**Observation**: Les employés sont responsables que des changement dans la table `client`.!!!

In [62]:
df_log.groupby("table_insert")["id_user"].unique()

table_insert
dim_customers    [0859b70a9ca905a870bfccc5f8440ba1, c4f0909120c...
dim_employees                                [integration_user_id]
dim_products                                 [integration_user_id]
fact_sales                                   [integration_user_id]
Name: id_user, dtype: object

## 🏷️: id_ligne
L'ID de la ligne affectée (EAN, customer_id...)

In [63]:
display_stats(df_log, columns='id_ligne')

---

**Colonne: id_ligne**

🔍 Type réel: object
📊 Mémoire: 16.61 MB
Longueur min du texte: 10
Longueur max du texte: 35
Valeurs uniques: 41981
Valeurs les plus fréquentes:

                                     count
id_ligne
ZY25L294165VSUG1H6WFSA2I2F3BBZCX8IH      5
ZWO17W93AH98OZTDLUBU9ALJAD2WBPJXDM0      5
ZW0KMLQUC46P2HPUK0J9BTLD0BW9NCW5YNB      5
ZUV66HD6XUO0U7EDS3B6P3GDO72LQPN45KP      5
ZN3CNG47EEX6BEVS2V5HPXRVVP8M76JZRFW      5

✅ Pas de valeurs manquantes dans la colonne 'id_ligne'

In [64]:
# Vérification de l'existance des notation scientiques
mask = df_log["id_ligne"].astype(str).str.contains("E\\+", case=False, na=False)
df_log.loc[mask, ["table_insert", "id_ligne"]].head()

Empty DataFrame
Columns: [table_insert, id_ligne]
Index: []

In [65]:
display_stats(df_log, columns='id_ligne')

---

**Colonne: id_ligne**

🔍 Type réel: object
📊 Mémoire: 16.61 MB
Longueur min du texte: 10
Longueur max du texte: 35
Valeurs uniques: 41981
Valeurs les plus fréquentes:

                                     count
id_ligne
ZY25L294165VSUG1H6WFSA2I2F3BBZCX8IH      5
ZWO17W93AH98OZTDLUBU9ALJAD2WBPJXDM0      5
ZW0KMLQUC46P2HPUK0J9BTLD0BW9NCW5YNB      5
ZUV66HD6XUO0U7EDS3B6P3GDO72LQPN45KP      5
ZN3CNG47EEX6BEVS2V5HPXRVVP8M76JZRFW      5

✅ Pas de valeurs manquantes dans la colonne 'id_ligne'

## 🏷️: champs

In [66]:
display_stats(df_log, columns='champs')

---

**Colonne: champs**

🔍 Type réel: object
📊 Mémoire: 11.16 MB
Longueur min du texte: 3
Longueur max du texte: 16
Valeurs uniques: 8
Valeurs les plus fréquentes:

             count
champs
CUSTUMER_ID  41377
Date         41377
EAN          41377
id_employe   41377
ID ticket    41377

⚠️ Il y a 2 valeurs manquantes dans la colonne 'champs' soit 0.0%

**Observation** : Les lignes où le champ n’est pas précisé correspondent à des opérations de `DELETE`. C’est tout à fait normal.

In [67]:
df_log['champs'].unique()

array(['date_inscription', 'prix', 'hash_mdp', nan, 'CUSTUMER_ID',
       'id_employe', 'EAN', 'Date', 'ID ticket'], dtype=object)

In [68]:
# On s'assure qu'il s'agit de la date de vente avant le mapper
mask = df_log["champs"] == 'Date'
df_log.loc[mask,'table_insert'].unique()

array(['fact_sales'], dtype=object)

In [69]:
n_before = df_log["champs"].isna().sum()

# Mapping des champs
field_map = {
    'date_inscription': 'subscription_date',
    'prix': 'unit_price',
    'hash_mdp': 'hash_mdp', # Colonne supprimée
    'CUSTUMER_ID': 'customer_id',
    'id_employe': 'employee_id',
    'EAN': 'ean',
    'Date': 'date_id', # Attention, ce 'Date' est différent de celui des logs
    'ID ticket': 'ticket_id'
}

df_log['champs'] = df_log['champs'].map(field_map)

n_injected = df_log["champs"].isna().sum() - n_before
if n_injected > 0 :
    print(f"❌ ERREUR : {n_injected} ligne(s) ne sont pas mappés.")
else:
    print("✅ Succès : Tous les champs sont mappés correctement !")

✅ Succès : Tous les champs sont mappés correctement !

In [70]:
mask = df_log["champs"].isna()
df_log.loc[mask,]

,id_user,date,action,table_insert,id_ligne,champs,detail,date_date
602,integration_user_id,45518,DELETE,dim_employees,c3d4e5f6789a0b1c2def3456789abcde1,NaN,NaN,2024-08-14
603,integration_user_id,45518,DELETE,dim_employees,f6e7d8c9b0a1e2d3f456789abc1234567,NaN,NaN,2024-08-14

In [71]:
display_stats(df_log, columns='champs')

---

**Colonne: champs**

🔍 Type réel: object
📊 Mémoire: 11.32 MB
Longueur min du texte: 3
Longueur max du texte: 17
Valeurs uniques: 8
Valeurs les plus fréquentes:

             count
champs
customer_id  41377
date_id      41377
ean          41377
employee_id  41377
ticket_id    41377

⚠️ Il y a 2 valeurs manquantes dans la colonne 'champs' soit 0.0%

## 🏷️: detail
Contient la valeur qui a été modifiée ou insérée.

In [72]:
display_stats(df_log, columns='detail')

---

**Colonne: detail**

🔍 Type réel: object
📊 Mémoire: 11.84 MB
Longueur min du texte: 1
Longueur max du texte: 32
Valeurs uniques: 20698
Valeurs les plus fréquentes:

                                  count
detail
45518                             41377
f491076a1ff2d873ebea809c11144542   1100
e01e752175e05f00c8314ccb8da4c418   1077
8d1001fbad3d2a60ff7530600ed5d55e    951
a7ada0770091e838e3dcd45265282820    943

⚠️ Il y a 2 valeurs manquantes dans la colonne 'detail' soit 0.0%

In [73]:
mask_unit_price = (df_log['champs'] == 'unit_price')
mask_bad_price = pd.isna(df_log['detail'])

# On sélectionne les lignes qui SONT des prix ET qui sont quand même NaN
bad_price_rows = df_log.loc[mask_unit_price & mask_bad_price, ['champs', 'detail']]

if bad_price_rows.empty:  
    print("✅ Tous les prix sont corrigés")
else:
    n = len(bad_price_rows) 
    print(f"❌ {n} prix semblent être enregistrés sous forme de date ou texte.")
    display(bad_price_rows)

✅ Tous les prix sont corrigés

In [74]:
# Vérification de l'existance des notation scientiques
mask = df_log["detail"].astype(str).str.contains("E\\+", case=False, na=False)
df_log.loc[mask, ["table_insert", "detail"]].head()

Empty DataFrame
Columns: [table_insert, detail]
Index: []

### Correction des prix stockés sous forme de text

In [75]:
mask_unit_price = (df_log['champs'] == 'unit_price')
df_log.loc[mask_unit_price, 'detail'] = pd.to_numeric(df_log.loc[mask_unit_price, 'detail'], errors='coerce')

mask_bad_price = pd.isna(df_log['detail'])
# On sélectionne les lignes qui SONT des prix ET qui sont quand même NaN
bad_price_rows = df_log.loc[mask_unit_price & mask_bad_price, ['champs', 'detail']]

if bad_price_rows.empty:  
    print("✅ Tous les prix sont corrigés")
else:
    n = len(bad_price_rows) 
    print(f"❌ {n} prix semblent être enregistrés sous forme de date ou texte.")
    display(bad_price_rows)

✅ Tous les prix sont corrigés

### Correction des EAN stocké en notation scientifique

In [76]:
# Vérification de l'existance des notation scientiques
mask = df_log["detail"].astype(str).str.contains("E\\+", case=False, na=False)
df_log.loc[mask, ["table_insert", "detail"]].head()

Empty DataFrame
Columns: [table_insert, detail]
Index: []

In [77]:
display_stats(df_log, columns='detail')

---

**Colonne: detail**

🔍 Type réel: object
📊 Mémoire: 11.84 MB
Longueur min du texte: 3
Longueur max du texte: 32
Valeurs uniques: 20698
Valeurs les plus fréquentes:

                                  count
detail
45518                             41377
f491076a1ff2d873ebea809c11144542   1100
e01e752175e05f00c8314ccb8da4c418   1077
8d1001fbad3d2a60ff7530600ed5d55e    951
a7ada0770091e838e3dcd45265282820    943

⚠️ Il y a 2 valeurs manquantes dans la colonne 'detail' soit 0.0%

### Correction des EAN stocké en notation scientifique

In [78]:
# Vérification de l'existance des notation scientiques
mask = df_log["detail"].astype(str).str.contains("E\\+", case=False, na=False)
df_log.loc[mask, ["table_insert", "detail"]].head()

Empty DataFrame
Columns: [table_insert, detail]
Index: []

In [79]:
display_stats(df_log, columns='detail')

---

**Colonne: detail**

🔍 Type réel: object
📊 Mémoire: 11.84 MB
Longueur min du texte: 3
Longueur max du texte: 32
Valeurs uniques: 20698
Valeurs les plus fréquentes:

                                  count
detail
45518                             41377
f491076a1ff2d873ebea809c11144542   1100
e01e752175e05f00c8314ccb8da4c418   1077
8d1001fbad3d2a60ff7530600ed5d55e    951
a7ada0770091e838e3dcd45265282820    943

⚠️ Il y a 2 valeurs manquantes dans la colonne 'detail' soit 0.0%

# 🗄️MIGRATION DES DONNEES

## Connexion au serveur Postgres

In [80]:
# Chargement des variables d'environnement depuis .env
from dotenv import load_dotenv
load_dotenv(dotenv_path='../.env')

db_user     = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')
db_host     = os.getenv('DB_HOST', 'localhost')
db_port     = os.getenv('DB_PORT', '5432')
db_name     = os.getenv('DB_NAME')

# Construction de la chaîne de connexion
# Format: dialect+driver://username:password@host:port/database
connection_string = f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"

In [81]:
# CRÉATION DU MOTEUR DE CONNEXION ET TEST ---
print(f"Tentative de connexion à la base de données: {db_name}")
try:
    engine = create_engine(connection_string)

    with engine.connect() as connection:
        print("✅ Connexion à la base de données supersmart_poc réussie !")
        
except Exception as e:
    print(f"❌ Échec de la connexion à la base de données.")
    print(f"Erreur: {e}")
    # On arrête le script si la connexion échoue, car rien ne pourra fonctionner
    sys.exit()

Tentative de connexion à la base de données: supersmart_poc
✅ Connexion à la base de données supersmart_poc réussie !

In [82]:
# ==============================================================================
# === Fonction de chargement intelligente
# ==============================================================================
def load_data_if_empty(dataframe, table_name, engine):
    """
    Vérifie si une table est vide. Si c'est le cas, charge les données du DataFrame.
    Sinon, ignore le chargement.
    """
    inspector = inspect(engine)
    
    # On vérifie d'abord si la table existe et si elle contient des lignes
    if inspector.has_table(table_name, schema='public'):
        with engine.connect() as connection:
            count = connection.execute(text(f"SELECT COUNT(1) FROM public.{table_name}")).scalar()
            if count > 0:
                print(f"ℹ️ La table '{table_name}' contient déjà {count} lignes. Chargement ignoré.")
                return # On arrête la fonction ici
    
    # Si la table n'existe pas ou est vide, on la charge
    try:
        print(f"--- La table '{table_name}' est vide. Début du chargement... ---")
        dataframe.to_sql(
            name=table_name,
            con=engine,
            schema='public',
            if_exists='append', # 'append' est sûr, car on sait que la table est vide
            index=False
        )
        print(f"✅ La table '{table_name}' a été populée avec succès !")
    except Exception as e:
        print(f"❌ Une erreur est survenue lors du chargement de '{table_name}'.")
        print(f"Erreur: {e}")

## Migration de la table `Calendrier` vers `dim_calendar`

In [83]:
# ==============================================================================
# === ETAPE 1 : Préparation des données
# ==============================================================================
df_calendar_clean = df_calendrier.copy()

# Mapping des champs
rename_map = {
    'date': 'date_id',
    'annee': 'year',
    'mois': 'month',
    'Jour': 'day_of_month', # format de la colonne a été corrigé plus haut dans la section spécifique à la colonne
    'mois_nom': 'month_name',
    'jour_semaine': 'day_of_week',
    'trimestre': 'quarter'
}
df_calendar_clean = df_calendar_clean.rename(columns=rename_map)
print("Colonnes renommées.")

# Sélectionner les colonnes pour correspondre à notre table SQL finale
# La colonne 'annee_mois' est exclue de la base
final_columns = [
    'date_id', 'year', 'month', 'day_of_month', 
    'month_name', 'day_of_week', 'quarter',
    'full_date' # champ calculé ajouté
]
df_calendar_clean = df_calendar_clean[final_columns]
print("DataFrame final pour dim_calendar est prêt.")


# ==============================================================================
# === ETAPE 2 : Population de la nouvelle table dim_calendar
# ==============================================================================
load_data_if_empty(df_calendar_clean, 'dim_calendar', engine)

Colonnes renommées.
DataFrame final pour dim_calendar est prêt.
--- La table 'dim_calendar' est vide. Début du chargement... ---
✅ La table 'dim_calendar' a été populée avec succès !

## Migration de la table `Clients` vers `dim_customers`

In [84]:
# ==============================================================================
# === ETAPE 1 : Préparation des données
# ==============================================================================

df_customers_clean = df_client.copy()

# Mapping des champs
rename_map = {
    'CUSTUMER_ID': 'customer_id', # Correction de la faute de frappe "CUSTUMER"
    'date_inscription': 'subscription_date'
}
df_customers_clean = df_customers_clean.rename(columns=rename_map)
print("Colonnes renommées.")

# Sélectionner les colonnes finales
final_columns = ['customer_id', 'subscription_date']
df_customers_clean = df_customers_clean[final_columns]
print("DataFrame final pour dim_customers est prêt.")

# ==============================================================================
# === ETAPE 2 : Population de la nouvelle table dim_customers
# ==============================================================================
load_data_if_empty(df_customers_clean, 'dim_customers', engine)

Colonnes renommées.
DataFrame final pour dim_customers est prêt.
--- La table 'dim_customers' est vide. Début du chargement... ---
✅ La table 'dim_customers' a été populée avec succès !

## Migration de la table `Employé` vers `dim_employees`

In [85]:
# ==============================================================================
# === ETAPE 1 : Préparation des données
# ==============================================================================
df_employees_clean = df_employe.copy()

# Mapping des champs
rename_map = {
    'id_employe': 'employee_id',
    'employe': 'username',
    'prenom': 'first_name',
    'nom': 'last_name',
    'mail': 'email',
    'date_debut_date': 'start_date' # On prends la version convertie
}
df_employees_clean = df_employees_clean.rename(columns=rename_map)
print("Colonnes renommées.")

# Sélectionner les colonnes finales
# La colonne 'hash_mdp' est exclue de la base
final_columns = ['employee_id', 'username', 'first_name', 'last_name', 'start_date', 'email']
df_employees_clean = df_employees_clean[final_columns]
print("DataFrame final pour dim_employees est prêt.")

# ==============================================================================
# === ETAPE 2 : Population de la nouvelle table dim_employees
# ==============================================================================
load_data_if_empty(df_employees_clean, 'dim_employees', engine)

Colonnes renommées.
DataFrame final pour dim_employees est prêt.
--- La table 'dim_employees' est vide. Début du chargement... ---
✅ La table 'dim_employees' a été populée avec succès !

## Migration de la table `Produits` vers `dim_products`

In [86]:
# ==============================================================================
# === ETAPE 1 : Préparation des données
# ==============================================================================
df_products_clean = df_produit.copy()

# Mapping des champs
rename_map = {
    'EAN': 'ean',
    'categorie': 'category',
    'Rayon': 'department',
    'Libelle_produit': 'product_label',
    'prix': 'unit_price'
}
df_products_clean = df_products_clean.rename(columns=rename_map)
print("Colonnes renommées.")

# Valider les données 
# On supprime les lignes où le prix est manquant (NULL) ou négatif,
# pour respecter les contraintes NOT NULL et CHECK de la BDD.
initial_rows = len(df_products_clean)
df_products_clean.dropna(subset=['unit_price'], inplace=True)
df_products_clean = df_products_clean[df_products_clean['unit_price'] >= 0]
final_rows = len(df_products_clean)

if initial_rows != final_rows:
    print(f"⚠️ {initial_rows - final_rows} produits ont été exclus (prix manquant ou négatif).")

# Sélectionner les colonnes finales
final_columns = ['ean', 'category', 'department', 'product_label', 'unit_price']
df_products_clean = df_products_clean[final_columns]
print("DataFrame final pour dim_products est prêt.")

# ==============================================================================
# === ETAPE 2 : Population de la nouvelle table dim_products
# ==============================================================================
load_data_if_empty(df_products_clean, 'dim_products', engine)

Colonnes renommées.
DataFrame final pour dim_products est prêt.
--- La table 'dim_products' est vide. Début du chargement... ---
✅ La table 'dim_products' a été populée avec succès !

## Chargement de fichier log dans la table `app_logs`

In [87]:
# ==============================================================================
# === ETAPE 1 : Préparation des données
# ==============================================================================


df_log_clean = df_log.copy()

# Mapping des champs (source | cible)
rename_map = {
    'id_user': 'user_id',
    'date_date': 'log_date',
    'action': 'action_type',
    'table_insert': 'table_name',
    'id_ligne': 'row_id',
    'champs': 'field_name',
    'detail': 'new_value'
}

df_log_clean = df_log_clean.rename( columns = rename_map)
print("Colonnes renommées")

# Sélectionner les colonnes finales
final_columns = [
    'user_id', 'log_date', 'action_type', 'table_name', 
    'row_id', 'field_name', 'new_value'
]

df_log_clean = df_log_clean[final_columns]
print("DataFrame final pour app_logs est prêt.")


# ==============================================================================
# === ETAPE 2 : Population de la nouvelle table fact_sales
# ==============================================================================
load_data_if_empty(df_log_clean, 'app_logs', engine)

Colonnes renommées
DataFrame final pour app_logs est prêt.
--- La table 'app_logs' est vide. Début du chargement... ---
✅ La table 'app_logs' a été populée avec succès !

## Migration de la table `Ventes` vers `fact_sales`

In [88]:
# ==============================================================================
# === ETAPE 1 : Préparation des données
# ==============================================================================
print("\n--- Début de la transformation de la table des Ventes ---")

df_sales_clean = df_vente.copy()

# Ajout des nouveaux champs


# Mapping des champs
rename_map = {
    'ID_BDD': 'sale_id',
    'CUSTOMER_ID': 'customer_id',
    'id_employe': 'employee_id',
    'EAN': 'ean',
    'Date achat': 'date_id',
    'ID ticket': 'ticket_id'
}
df_sales_clean = df_sales_clean.rename(columns=rename_map)
print("Colonnes renommées.")

# Ajout des colonnes supplémentaires
df_sales_clean["quantity"] = 1

# Ajout des prix unitaire dans la table vente
df_sales_clean = pd.merge(
    df_sales_clean,
    df_products_clean[['ean','unit_price']],
    on = 'ean',
    how='left'
)

df_sales_clean['load_timestamp'] = pd.Timestamp.now() # 

late_sales_ids = df_log_clean.loc[
    (df_log_clean['log_date'] == '2024-08-15') &
    (df_log_clean['table_name'] == 'fact_sales') &
    (df_log_clean['action_type'] == 'INSERT'),
    'row_id'
].unique()

df_sales_clean['transaction_type'] = 'INITIAL_SALE'

df_sales_clean.loc[df_sales_clean['sale_id'].isin(late_sales_ids), 'transaction_type'] = 'ADJUSTMENT'

nan_count = df_sales_clean["unit_price"].isna().sum()
if nan_count > 0:
    raise ValueError(f"Dans la table de vente, {nan_count} valeurs manquantes détectées dans unit_price.")


# Sélectionner les colonnes finales
final_columns = [
    'sale_id', 'customer_id', 'employee_id', 'ean', 'date_id', 'ticket_id',
    'quantity', 'unit_price', 'transaction_type', 'load_timestamp'
]
df_sales_clean = df_sales_clean[final_columns]
print("DataFrame final pour fact_sales est prêt.")

# ==============================================================================
# === ETAPE 2 : Population de la nouvelle table fact_sales
# ==============================================================================

load_data_if_empty(df_sales_clean, 'fact_sales', engine)

--- Début de la transformation de la table des Ventes ---
Colonnes renommées.
DataFrame final pour fact_sales est prêt.
--- La table 'fact_sales' est vide. Début du chargement... ---
✅ La table 'fact_sales' a été populée avec succès !